services:
  postgres:
    image: postgres:16-alpine
    container_name: deployboard-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: deployboard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/sql:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: deployboard-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env.docker.example
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  prometheus:
    image: prom/prometheus:latest
    container_name: deployboard-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: deployboard-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      GF_SERVER_ROOT_URL: http://localhost/grafana/
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana

  nginx:
    image: nginx:alpine
    container_name: deployboard-nginx
    restart: unless-stopped

    ports:
      - "80:80"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - backend
      - grafana

volumes:
  postgres_data:
  grafana_data: