server {
    listen 80;

    location / {
        return 200 'DeployBoard NGINX Reverse Proxy Running';
        add_header Content-Type text/plain;
    }

    location /api/ {
        proxy_pass http://backend:5000/api/;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /health {
        proxy_pass http://backend:5000/health;
    }

    location /metrics {
        proxy_pass http://backend:5000/metrics;
    }

    location /grafana/ {
        proxy_pass http://grafana:3000/grafana/;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location = /grafana {
        return 301 /grafana/;
    }
}
